apiVersion: v1
kind: Service
metadata:
  name: bluegreen-test-svc
spec:
  type: NodePort
  selector:
    app: bluegreen-test
    color: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001