apiVersion: v1
kind: Service
metadata:
  name: green-svc
spec:
  type: NodePort
  selector:
    app: bluegreen-test
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002