apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-dummy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: dummy
  hostPath:
    path: /etc/hostPath
    type: Directory