apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voldata
spec:
  capacity:
    storage: 1Gi
  storageClassName: host
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/voldata
    type: Directory