apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600']
    livenessProbe:
      exec:
        command: ['cat', '/tmp/healthy']
      initialDelaySeconds: 5
      periodSeconds: 5